FROM python:3.10-slim

RUN mkdir /tests
WORKDIR /tests

# Скопируйте файл зависимостей и установите их
COPY requirements.txt .
RUN pip install -r requirements.txt

COPY . .


CMD ["python", "migrations.py"]
CMD ["pytest"]
