version: '3'

services:
  db:
    image: postgres:15.1-alpine
    container_name: db_app
    # ports: 
    #   - "5437:5432"
    command: -p 1221
    expose: 
      - 1221
    env_file: 
      - .env

  pytest:
    build:
      context: .
      dockerfile: Dockerfile.test
    container_name: pytest_container
    depends_on:
      - db
