FROM python:3.10-slim

RUN mkdir /tests
WORKDIR /tests

# Скопируйте файл зависимостей и установите их
COPY requirements.txt .
RUN pip install -r requirements.txt

COPY . .


# CMD ["python", "models.py", "&&", "uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000"]
CMD ["pytest"]
